### ISSUE TITLE
URLFetchingError at /resume/generate

### ISSUE THREAD

**Issue by vossisboss** [adinhodovic/wagtail-resume#43]
Hello! Thank you for writing this code. I'm trying it with a new project and when I include it in a test project, I'm running into an issue with a URL fetching error for the "Generate PDF" button. The exception is URLError: <urlopen error [Errno 61] Connection refused>.

I definitely included the line in urls.py you included in the directions and as far as I can tell Weasyprint is functional. Do you happen to know anything else that might lead to an error like this?

Thanks again for this extension. I look forward to getting it working.

**Comment by adinhodovic** [comment]
Hey :)!

I've seen other have issues with generating pdfs when using gunicorn with less than 2 workers. PDF generating is heavy and the worker can block the whole server (making and subsequent requests fail), this is my guess, not sure. The PDF generation should probably be async, for now you should be able to bypass it with multiple workers to gunicorn (if that's being used):

`gunicorn config.wsgi --workers=2'`

I'll look into migrating this functionality to https://github.com/fdemmer/django-weasyprint.

Not super sure regarding this one, let me know if you have other ideas.

**Comment by OLGJ** [comment]
Hi. 
I had a similar issue like this for a few days! For me I had made all the configurations and yet I recieved an 
`Exception Type: URLFetchingError at /resume/generate
Exception Value: HTTPError: HTTP Error 400: Bad Request?`

Solution for me:
My PDF was in live + preview mode in the wagtail admin settings. Publishing it so it was only in live made it work (but make sure url configs are correct).
